{
    'data': [
        ('01_peopleplaneteconomy', 'People. Planet. Economy.'),
        ('02_systemicdysfunction', 'A System in Crisis'),
        ('03_keyplayers', 'Economic Actors'),
        ('04a_insight1', 'Open Questions 1'),
        ('04b_insight2', 'Open Questions 2'),
        ('04c_insight3', 'Open Questions 3'),
        ('05_d1shareholderprimacy', 'Diagnosis 1: Shareholder-Primacy'),
        ('06_movements_shareholderprimacy', 'Diagnosis 1: Movements'),
        ('07_d2performance', 'Diagnosis 2: Corporate Performance Management'),
        ('08_movements_performance', 'Diagnosis 2: Movements'),
        ('09_d3leadership', 'Diagnosis 3: Leadership & Education'),
        ('10_movements_leadership', 'Diagnosis 3: Movements'),
        ('11_allmovements', 'The Movements Landscape'),
        ('12_leversofchange', 'Incorporating Purpose: Levers of Change'),
        ('13_furtherreading', 'Research & Further Reading'),
        ('withoutmaps', 'A world without maps'),
        ('14_contactus', 'Give Feedback'),
    ],
    'lets': {
        'story': 'vm:story-{row[0].as_slug}',
        'first': 'vm:story-{row[0].as_slug}-1',
        'storyName': '{row[1]}',
        'version': '20200907',
    },
    'triples': [
        ('{story}', 'rdf:type', 'vm:Story'),
        ('{story}', 'vm:name', '{storyName}'),
        ('{story}', 'vm:usesMapTiles',
            'https://opatlas-live.s3.amazonaws.com/economicsystem/{version}/'
            'overlays/{row[0]}/{{z}}-{{x}}-{{y}}.png'),
        ('{story}', 'vm:firstPoint', '{first}'),
        ('{first}', 'rdf:type', 'vm:Storypoint'),
        ('{first}', 'vm:ofStory', '{story}'),
        ('{story}', 'vm:asOrdinal', '{n}'),
    ],
}
