{
    'data': [{
        'view_id': 'welcome_to_smp',
        'name': 'Welcome to the Shared Meaning Platform',
        'class': 'Story',
        'first_point': 'storypoints/111',
    }, {
        'view_id': 'storypoints/111',
        'of_story': 'welcome_to_smp',
        'geog_id': 'activity',
        'class': 'Storypoint',
    }, {
        'view_id': 'features_navigation',
        'name': 'Features & Navigation',
        'class': 'Story',
        'first_point': 'storypoints/121',
    }, {
        'view_id': 'storypoints/121',
        'of_story': 'features_navigation',
        'geog_id': 'activity',
        'class': 'Storypoint',
    }, {
        'view_id': 'activity_view',
        'name': 'Activity View',
        'geog_id': 'activity',
        'class': 'Story',
        'first_point': 'storypoints/131',
    }, {
        'view_id': 'storypoints/131',
        'of_story': 'activity_view',
        'class': 'Storypoint',
    }, {
        'view_id': 'geographic_view',
        'name': 'Geographic View',
        'class': 'Story',
        'first_point': 'storypoints/161',
    }, {
        'view_id': 'storypoints/161',
        'name': 'Topographical Map',
        'of_story': 'geographic_map',
        'class': 'Storypoint',
    }, {
        'view_id': 'feedback_smp',
        'name': 'Feedback',
        'class': 'Story',
        'first_point': 'storypoints/171',
    }, {
        'view_id': 'storypoints/171',
        'of_story': 'feedback_smp',
        'class': 'Storypoint',
    }, {
        'view_id': 'ris3_overview',
        'name': 'RIS3: Overview',
        'tile_id': 'ris3_overview',
        'bg': '#fff',
        'class': 'Story',
        'first_point': 'storypoints/211',
    }, {
        'view_id': 'storypoints/211',
        'of_story': 'ris3_overview',
        'class': 'Storypoint',
    }, {
        'view_id': 'ris3_roadmap',
        'name': 'RIS3: Roadmap',
        'tile_id': 'ris3_roadmap',
        'bg': '#fff',
        'class': 'Story',
        'first_point': 'storypoints/221',
    }, {
        'view_id': 'storypoints/221',
        'geog_id': 'ris3_roadmap',
        'of_story': 'ris3_roadmap',
        'class': 'Storypoint',
    }, {
        'view_id': 'ris3_asset_classes',
        'name': 'RIS3: Asset classes',
        'tile_id': 'ris3_asset_classes',
        'bg': '#fff',
        'class': 'Story',
        'first_point': 'storypoints/231',
    }, {
        'view_id': 'storypoints/231',
        'geog_id': 'ris3_asset_classes',
        'of_story': 'ris3_asset_classes',
        'class': 'Storypoint',
    }, {
        'view_id': 'ris3_risk_maps',
        'name': 'Risk Maps',
        'tile_id': 'ris3_risk_maps',
        'bg': '#fff',
        'class': 'Story',
        'first_point': 'storypoints/241',
    }, {
        'view_id': 'storypoints/241',
        'name': 'Root Cause',
        'tile_id': 'ris3_risk_maps_root_causes',
        'bg': 'transparent',
        'of_story': 'ris3_risk_maps',
        'next_point': 'storypoints/242',
        'class': 'Storypoint',
    }, {
        'view_id': 'storypoints/242',
        'name': 'Failure Modes',
        'tile_id': 'ris3_risk_maps_failure_modes',
        'bg': 'transparent',
        'of_story': 'ris3_risk_maps',
        'next_point': 'storypoints/243',
        'class': 'Storypoint',
    }, {
        'view_id': 'storypoints/243',
        'name': 'Asset Failure Impacts',
        'tile_id': 'ris3_risk_maps_asset_failure_impacts',
        'bg': 'transparent',
        'of_story': 'ris3_risk_maps',
        'next_point': 'storypoints/244',
        'class': 'Storypoint',
    }, {
        'view_id': 'storypoints/244',
        'name': 'Service Impacts',
        'tile_id': 'ris3_risk_maps_service_impacts',
        'bg': 'transparent',
        'of_story': 'ris3_risk_maps',
        'next_point': 'storypoints/245',
        'class': 'Storypoint',
    }, {
        'view_id': 'storypoints/245',
        'name': 'Risk Map',
        'tile_id': 'ris3_risk_maps_risk_map',
        'bg': 'transparent',
        'of_story': 'ris3_risk_maps',
        'next_point': 'storypoints/246',
        'class': 'Storypoint',
    }, {
        'view_id': 'storypoints/246',
        'name': 'Capital Renewal',
        'tile_id': 'ris3_risk_map_capital_renewal',
        'bg': 'transparent',
        'of_story': 'ris3_risk_maps',
        'next_point': 'storypoints/247',
        'class': 'Storypoint',
    }, {
        'view_id': 'storypoints/247',
        'name': 'Capital Renewal Risk Map',
        'tile_id': 'ris3_risk_map_capital_renewal_risk_map',
        'bg': 'transparent',
        'of_story': 'ris3_risk_maps',
        'class': 'Storypoint',
    }, {
        'view_id': 'key_concept_service_value',
        'name': 'Key Concept 1: Service value',
        'tile_id': 'key_concept_service_value',
        'bg': '#fff',
        'class': 'Story',
        'first_point': 'storypoints/311',
    }, {
        'view_id': 'storypoints/311',
        'geog_id': 'key_concept_service_value',
        'of_story': 'key_concept_service_value',
        'class': 'Storypoint',
    }, {
        'view_id': 'key_concept_customer_engagement',
        'name': 'Key Concept 2: Customer Engagement',
        'tile_id': 'key_concept_customer_engagement',
        'bg': '#fff',
        'class': 'Story',
        'first_point': 'storypoints/321',
    }, {
        'view_id': 'storypoints/321',
        'geog_id': 'key_concept_customer_engagement',
        'of_story': 'key_concept_customer_engagement',
        'class': 'Storypoint',
    }, {
        'view_id': 'key_concept_criticality',
        'name': 'Key Concept 3: Criticality',
        'tile_id': 'key_concept_criticality',
        'bg': '#fff',
        'class': 'Story',
        'first_point': 'storypoints/331',
    }, {
        'view_id': 'storypoints/331',
        'geog_id': 'key_concept_criticality',
        'of_story': 'key_concept_criticality',
        'class': 'Storypoint',
    }, {
        'view_id': 'key_concept_whole_life_cost',
        'name': 'Key Concept 4: Whole-life cost',
        'tile_id': 'key_concept_whole_life_cost',
        'bg': '#fff',
        'class': 'Story',
        'first_point': 'storypoints/341',
    }, {
        'view_id': 'storypoints/341',
        'geog_id': 'key_concept_whole_life_cost',
        'of_story': 'key_concept_whole_life_cost',
        'class': 'Storypoint',
    }, {
        'view_id': 'key_concept_data_for_decision_making',
        'name': 'Key Concept 5: Data for decision-making',
        'tile_id': 'key_concept_data_for_decision_making',
        'bg': '#fff',
        'class': 'Story',
        'first_point': 'storypoints/351',
    }, {
        'view_id': 'storypoints/351',
        'geog_id': 'key_concept_data_for_decision_making',
        'of_story': 'key_concept_data_for_decision_making',
        'class': 'Storypoint',
    }, {
        'view_id': 'pavements_overview',
        'name': 'Pavements: Overview',
        'tile_id': 'pavements_overview',
        'bg': '#fff',
        'class': 'Story',
        'first_point': 'storypoints/411',
    }, {
        'view_id': 'storypoints/411',
        'geog_id': 'pavements_overview',
        'of_story': 'pavements_overview',
        'class': 'Storypoint',
    }, {
        'view_id': 'pavements_risk_map',
        'name': 'Pavements: Risk Map',
        'tile_id': 'pavements_risk_map',
        'bg': '#fff',
        'class': 'Story',
        'first_point': 'storypoints/421',
    }, {
        'view_id': 'storypoints/421',
        'geog_id': 'pavements_risk_map',
        'of_story': 'pavements_risk_map',
        'class': 'Storypoint',
    }, {
        'view_id': 'pavements_data_flows',
        'name': 'Pavements: Data Flows',
        'tile_id': 'pavements_data_flows',
        'bg': '#fff',
        'class': 'Story',
        'first_point': 'storypoints/431',
    }, {
        'view_id': 'storypoints/431',
        'geog_id': 'pavements_data_flows',
        'of_story': 'pavements_data_flows',
        'class': 'Storypoint',
    }, {
        'view_id': 'pavements_investment_case',
        'name': 'Pavements: Investment Case',
        'tile_id': 'pavements_investment_case',
        'bg': '#fff',
        'class': 'Story',
        'first_point': 'storypoints/441',
    }, {
        'view_id': 'storypoints/441',
        'geog_id': 'pavements_investment_case',
        'of_story': 'pavements_investment_case',
        'class': 'Storypoint',
    }, {
        'view_id': 'structures_approach',
        'name': 'Approach',
        'tile_id': 'structures_approach',
        'bg': '#fff',
        'class': 'Story',
        'first_point': 'storypoints/611',
    }, {
        'view_id': 'storypoints/611',
        'geog_id': 'structures_approach',
        'of_story': 'structures_approach',
        'class': 'Storypoint',
    }, {
        'view_id': 'ris3_systemic_patterns_performance_resources',
        'name': 'Performance & Resources',
        'tile_id': 'ris3_systemic_patterns_performance_resources',
        'bg': '#fff',
        'class': 'Story',
        'first_point': 'storypoints/511',
    }, {
        'view_id': 'storypoints/511',
        'geog_id': 'ris3_systemic_patterns_performance_resources',
        'of_story': 'ris3_systemic_patterns_performance_resources',
        'class': 'Storypoint',
    }, {
        'view_id': 'ris3_systemic_patterns_standards_deviations',
        'name': 'SES Consultation & Deviation Requests',
        'tile_id': 'ris3_systemic_patterns_standards_deviations',
        'bg': '#fff',
        'class': 'Story',
        'first_point': 'storypoints/521',
    }, {
        'view_id': 'storypoints/521',
        'geog_id': 'ris3_systemic_patterns_standards_deviations',
        'of_story': 'ris3_systemic_patterns_standards_deviations',
        'class': 'Storypoint',
    }, {
        'view_id': 'ris3_systemic_patterns_data_trust_issues',
        'name': 'Data quality and system replacement',
        'tile_id': 'ris3_systemic_patterns_data_trust_issues',
        'bg': '#fff',
        'class': 'Story',
        'first_point': 'storypoints/531',
    }, {
        'view_id': 'storypoints/531',
        'geog_id': 'ris3_systemic_patterns_data_trust_issues',
        'of_story': 'ris3_systemic_patterns_data_trust_issues',
        'class': 'Storypoint',
    }],
    'lets': {
        'iri': 'vm:{row[view_id]}',
        'version': '20210401',
    },
    'triples': [
        ('{iri}', 'rdf:type', 'vm:{row[class]}'),
        ('{iri}', 'vm:name', '{row[name].as_text}'),
        ('{iri}', 'vm:usesMapTiles',
            'https://opatlas-live.s3.amazonaws.com/ris3-renewals/{version}/'
            'overlays/{row[tile_id].as_text}/{{z}}-{{x}}-{{y}}.png#'
            'background:{row[bg].as_text}'),
        ('{iri}', 'vm:useFilters', '{row[filters].as_text}'),
        ('{iri}', 'vm:followedBy', '{row[following].as_text}'),
        ('{iri}', 'vm:ofStory', 'vm:{row[of_story].as_text}'),
        ('{iri}', 'vm:firstPoint', 'vm:{row[first_point].as_text}'),
        ('{iri}', 'vm:followedBy', 'vm:{row[next_point].as_text}'),
        ('{iri}', 'vm:asOrdinal', '{n}'),
        ('{iri}', 'vm:comment', '{row[geog_id].as_text}'),
    ],
}
