{
    'data': [{
        'view_id': 'welcome_to_smp',
        'name': 'Welcome to the Shared Meaning Platform',
        'class': 'Story',
        'first_point': 'storypoints/1101',
    }, {
        'view_id': 'storypoints/1101',
        'of_story': 'welcome_to_smp',
        'geog_id': 'activity',
        'next_point': 'storypoints/1106',
        'class': 'Storypoint',
    }, {
        'view_id': 'storypoints/1106',
        'of_story': 'welcome_to_smp',
        'tile_id': 'welcome_to_smp_operational',
        'bg': 'transparent',
        'geog_id': 'activity',
        'next_point': 'storypoints/1107',
        'class': 'Storypoint',
    }, {
        'view_id': 'storypoints/1107',
        'of_story': 'welcome_to_smp',
        'tile_id': 'welcome_to_smp_enabling',
        'bg': 'transparent',
        'geog_id': 'activity',
        'next_point': 'storypoints/1108',
        'class': 'Storypoint',
    }, {
        'view_id': 'storypoints/1108',
        'of_story': 'welcome_to_smp',
        'tile_id': 'welcome_to_smp_management',
        'bg': 'transparent',
        'geog_id': 'activity',
        'class': 'Storypoint',
    }, {
        'view_id': 'features_navigation',
        'name': 'Features & Navigation',
        'class': 'Story',
        'first_point': 'storypoints/1201',
    }, {
        'view_id': 'storypoints/1201',
        'of_story': 'features_navigation',
        'geog_id': 'activity',
        'class': 'Storypoint',
    }, {
        'view_id': 'activity_view',
        'name': 'Activity View',
        'class': 'Story',
        'first_point': 'storypoints/1301',
    }, {
        'view_id': 'storypoints/1301',
        'of_story': 'activity_view',
        'geog_id': 'activity',
        'class': 'Storypoint',
    }, {
        'view_id': 'geographic_view',
        'name': 'Geographic View',
        'class': 'Story',
        'first_point': 'storypoints/1601',
    }, {
        'view_id': 'storypoints/1601',
        'name': 'Topographical Map',
        'tile_id': 'geographic_map_topographical',
        'bg': '#fff',
        'of_story': 'geographic_map',
        'next_point': 'storypoints/1602',
        'class': 'Storypoint',
    }, {
        'view_id': 'storypoints/1602',
        'name': 'Motorways & A-Roads',
        'tile_id': 'geographic_map_motorways_a-roads',
        'bg': '#fff',
        'of_story': 'geographic_map',
        'next_point': 'storypoints/1603',
        'class': 'Storypoint',
    }, {
        'view_id': 'storypoints/1603',
        'name': 'Regions & Areas',
        'tile_id': 'geographic_map_regions_areas',
        'bg': '#fff',
        'of_story': 'geographic_map',
        'next_point': 'storypoints/1604',
        'class': 'Storypoint',
    }, {
        'view_id': 'storypoints/1604',
        'name': 'Routes',
        'tile_id': 'geographic_map_routes',
        'bg': '#fff',
        'of_story': 'geographic_map',
        'next_point': 'storypoints/1605',
        'class': 'Storypoint',
    }, {
        'view_id': 'storypoints/1605',
        'name': 'Subnational Transport Bodies',
        'tile_id': 'geographic_map_subnational_transport_bodies',
        'bg': '#fff',
        'of_story': 'geographic_map',
        'class': 'Storypoint',
    }, {
        'view_id': 'feedback_smp',
        'name': 'Feedback',
        'class': 'Story',
        'first_point': 'storypoints/1701',
    }, {
        'view_id': 'storypoints/1701',
        'of_story': 'feedback_smp',
        'class': 'Storypoint',
    }, {
        'view_id': 'ris3_overview',
        'name': 'RIS3: Overview',
        'tile_id': 'ris3_overview',
        'bg': '#002e5f',
        'class': 'Story',
        'first_point': 'storypoints/2101',
    }, {
        'view_id': 'storypoints/2101',
        'name': 'RIS3: Overview - Intro',
        'of_story': 'ris3_overview',
        'next_point': 'storypoints/2102',
        'geog_id': 'activity',
        'class': 'Storypoint',
    }, {
        'view_id': 'storypoints/2102',
        'name': 'RIS3: Overview - DfT',
        'of_story': 'ris3_overview',
        'next_point': 'storypoints/2103',
        'geog_id': 'activity',
        'class': 'Storypoint',
    }, {
        'view_id': 'storypoints/2103',
        'name': 'RIS3: Overview - ORR',
        'of_story': 'ris3_overview',
        'next_point': 'storypoints/2104',
        'geog_id': 'activity',
        'class': 'Storypoint',
    }, {
        'view_id': 'storypoints/2104',
        'name': 'RIS3: Overview - TF',
        'of_story': 'ris3_overview',
        'next_point': 'storypoints/2105',
        'geog_id': 'activity',
        'class': 'Storypoint',
    }, {
        'view_id': 'storypoints/2105',
        'name': 'RIS3: Overview - Board',
        'of_story': 'ris3_overview',
        'next_point': 'storypoints/2106',
        'geog_id': 'activity',
        'class': 'Storypoint',
    }, {
        'view_id': 'storypoints/2106',
        'name': 'RIS3: Overview - Stakeholder Engagement',
        'of_story': 'ris3_overview',
        'next_point': 'storypoints/2107',
        'geog_id': 'activity',
        'class': 'Storypoint',
    }, {
        'view_id': 'storypoints/2107',
        'name': 'RIS3: Overview - Funding',
        'of_story': 'ris3_overview',
        'next_point': 'storypoints/2108',
        'geog_id': 'activity',
        'class': 'Storypoint',
    }, {
        'view_id': 'storypoints/2108',
        'name': 'RIS3: Overview - Asset Classes',
        'of_story': 'ris3_overview',
        'next_point': 'storypoints/2109',
        'geog_id': 'activity',
        'class': 'Storypoint',
    }, {
        'view_id': 'storypoints/2109',
        'name': 'RIS3: Overview - Directorates',
        'tile_id': 'ris3_overview_directorates',
        'bg': 'transparent',
        'of_story': 'ris3_overview',
        'geog_id': 'activity',
        'class': 'Storypoint',
    }, {
        'view_id': 'ris3_roadmap',
        'name': 'RIS3: Roadmap',
        'tile_id': 'ris3_roadmap',
        'bg': '#002e5f',
        'class': 'Story',
        'first_point': 'storypoints/2201',
    }, {
        'view_id': 'storypoints/2201',
        'geog_id': 'ris3_roadmap',
        'of_story': 'ris3_roadmap',
        'class': 'Storypoint',
    }, {
        'view_id': 'ris3_asset_classes',
        'name': 'RIS3: Asset classes',
        'tile_id': 'ris3_asset_classes',
        'bg': '#fff',
        'class': 'Story',
        'first_point': 'storypoints/2301',
    }, {
        'view_id': 'storypoints/2301',
        'geog_id': 'ris3_asset_classes',
        'of_story': 'ris3_asset_classes',
        'class': 'Storypoint',
    }, {
        'view_id': 'ris3_risk_maps',
        'name': 'RIS3: Risk Maps',
        'tile_id': 'ris3_risk_maps',
        'bg': '#fff',
        'class': 'Story',
        'first_point': 'storypoints/2401',
    }, {
        'view_id': 'storypoints/2401',
        'name': 'RIS3: Risk Maps - Root Cause',
        'tile_id': 'ris3_risk_maps_root_causes',
        'bg': 'transparent',
        'of_story': 'ris3_risk_maps',
        'next_point': 'storypoints/2402',
        'class': 'Storypoint',
    }, {
        'view_id': 'storypoints/2402',
        'name': 'RIS3: Risk Maps - Failure Modes',
        'tile_id': 'ris3_risk_maps_failure_modes',
        'bg': 'transparent',
        'of_story': 'ris3_risk_maps',
        'next_point': 'storypoints/2403',
        'class': 'Storypoint',
    }, {
        'view_id': 'storypoints/2403',
        'name': 'RIS3: Risk Maps - Asset Failure Impacts',
        'tile_id': 'ris3_risk_maps_asset_failure_impacts',
        'bg': 'transparent',
        'of_story': 'ris3_risk_maps',
        'next_point': 'storypoints/2404',
        'class': 'Storypoint',
    }, {
        'view_id': 'storypoints/2404',
        'name': 'RIS3: Risk Maps - Service Impacts',
        'tile_id': 'ris3_risk_maps_service_impacts',
        'bg': 'transparent',
        'of_story': 'ris3_risk_maps',
        'next_point': 'storypoints/2405',
        'class': 'Storypoint',
    }, {
        'view_id': 'storypoints/2405',
        'name': 'RIS3: Risk Maps - Risk Map',
        'tile_id': 'ris3_risk_maps_service_impacts',
        'bg': 'transparent',
        'of_story': 'ris3_risk_maps',
        'next_point': 'storypoints/2406',
        'class': 'Storypoint',
    }, {
        'view_id': 'storypoints/2406',
        'name': 'RIS3: Capital Renewal',
        'tile_id': 'ris3_risk_map_capital_renewal',
        'bg': 'transparent',
        'of_story': 'ris3_risk_maps',
        'next_point': 'storypoints/2407',
        'class': 'Storypoint',
    }, {
        'view_id': 'storypoints/2407',
        'name': 'RIS3: Capital Renewal Risk Map',
        'tile_id': 'ris3_risk_map_capital_renewal',
        'bg': 'transparent',
        'of_story': 'ris3_risk_maps',
        'class': 'Storypoint',
    }, {
        'view_id': 'key_concept_service_value',
        'name': 'Key Concept 1: Service value',
        'tile_id': 'key_concept_service_value',
        'bg': '#002e5f',
        'class': 'Story',
        'first_point': 'storypoints/3101',
    }, {
        'view_id': 'storypoints/3101',
        'geog_id': 'key_concept_service_value',
        'of_story': 'key_concept_service_value',
        'class': 'Storypoint',
    }, {
        'view_id': 'key_concept_customer_engagement',
        'name': 'Key Concept 2: Customer Engagement',
        'tile_id': 'key_concept_customer_engagement',
        'bg': '#002e5f',
        'class': 'Story',
        'first_point': 'storypoints/3201',
    }, {
        'view_id': 'storypoints/3201',
        'geog_id': 'key_concept_customer_engagement',
        'of_story': 'key_concept_customer_engagement',
        'class': 'Storypoint',
    }, {
        'view_id': 'key_concept_criticality',
        'name': 'Key Concept 3: Criticality',
        'tile_id': 'key_concept_criticality',
        'bg': '#002e5f',
        'class': 'Story',
        'first_point': 'storypoints/3301',
    }, {
        'view_id': 'storypoints/3301',
        'geog_id': 'key_concept_criticality',
        'of_story': 'key_concept_criticality',
        'class': 'Storypoint',
    }, {
        'view_id': 'key_concept_whole_life_cost',
        'name': 'Key Concept 4: Whole-life cost',
        'tile_id': 'key_concept_whole_life_cost',
        'bg': '#002e5f',
        'class': 'Story',
        'first_point': 'storypoints/3401',
    }, {
        'view_id': 'storypoints/3401',
        'geog_id': 'key_concept_whole_life_cost',
        'of_story': 'key_concept_whole_life_cost',
        'class': 'Storypoint',
    }, {
        'view_id': 'key_concept_data_for_decision_making',
        'name': 'Key Concept 5: Data for decision-making',
        'tile_id': 'key_concept_data_for_decision_making',
        'bg': '#002e5f',
        'class': 'Story',
        'first_point': 'storypoints/3501',
    }, {
        'view_id': 'storypoints/3501',
        'geog_id': 'key_concept_data_for_decision_making',
        'of_story': 'key_concept_data_for_decision_making',
        'class': 'Storypoint',
    }, {
        'view_id': 'pavements_overview',
        'name': 'Pavements: Overview',
        'tile_id': 'pavements_overview',
        'bg': '#002e5f',
        'class': 'Story',
        'first_point': 'storypoints/4101',
    }, {
        'view_id': 'storypoints/4101',
        'geog_id': 'pavements_overview',
        'of_story': 'pavements_overview',
        'class': 'Storypoint',
    }, {
        'view_id': 'pavements_risk_map',
        'name': 'Pavements: Risk Map',
        'tile_id': 'pavements_risk_map',
        'bg': '#002e5f',
        'class': 'Story',
        'first_point': 'storypoints/4201',
    }, {
        'view_id': 'storypoints/4201',
        'geog_id': 'pavements_risk_map',
        'of_story': 'pavements_risk_map',
        'class': 'Storypoint',
    }, {
        'view_id': 'pavements_data_flows',
        'name': 'Pavements: Data Flows',
        'tile_id': 'pavements_data_flows',
        'bg': '#b3c1cf',
        'class': 'Story',
        'first_point': 'storypoints/4301',
    }, {
        'view_id': 'storypoints/4301',
        'geog_id': 'pavements_data_flows',
        'of_story': 'pavements_data_flows',
        'class': 'Storypoint',
    }, {
        'view_id': 'pavements_investment_case',
        'name': 'Pavements: Investment Case',
        'tile_id': 'pavements_investment_case',
        'bg': '#002e5f',
        'class': 'Story',
        'first_point': 'storypoints/4401',
    }, {
        'view_id': 'storypoints/4401',
        'geog_id': 'pavements_investment_case',
        'of_story': 'pavements_investment_case',
        'class': 'Storypoint',
    }, {
        'view_id': 'structures_approach',
        'name': 'Approach',
        'tile_id': 'structures_approach',
        'bg': '#002e5f',
        'class': 'Story',
        'first_point': 'storypoints/6101',
    }, {
        'view_id': 'storypoints/6101',
        'geog_id': 'structures_approach',
        'of_story': 'structures_approach',
        'class': 'Storypoint',
    }, {
        'view_id': 'ris3_systemic_patterns_performance_resources',
        'name': 'Performance & Resources',
        'tile_id': 'ris3_systemic_patterns_performance_resources',
        'bg': '#b3c1cf',
        'class': 'Story',
        'first_point': 'storypoints/5101',
    }, {
        'view_id': 'storypoints/5101',
        'geog_id': 'ris3_systemic_patterns_performance_resources',
        'of_story': 'ris3_systemic_patterns_performance_resources',
        'class': 'Storypoint',
    }, {
        'view_id': 'ris3_systemic_patterns_standards_deviations',
        'name': 'SES Consultation & Deviation Requests',
        'tile_id': 'ris3_systemic_patterns_standards_deviations',
        'bg': '#b3c1cf',
        'class': 'Story',
        'first_point': 'storypoints/5201',
    }, {
        'view_id': 'storypoints/5201',
        'geog_id': 'ris3_systemic_patterns_standards_deviations',
        'of_story': 'ris3_systemic_patterns_standards_deviations',
        'class': 'Storypoint',
    }, {
        'view_id': 'ris3_systemic_patterns_data_trust_issues',
        'name': 'Data quality and system replacement',
        'tile_id': 'ris3_systemic_patterns_data_trust_issues',
        'bg': '#b3c1cf',
        'class': 'Story',
        'first_point': 'storypoints/5301',
    }, {
        'view_id': 'storypoints/5301',
        'geog_id': 'ris3_systemic_patterns_data_trust_issues',
        'of_story': 'ris3_systemic_patterns_data_trust_issues',
        'class': 'Storypoint',
    }],
    'lets': {
        'iri': 'vm:{row[view_id]}',
        'version': '20210401',
    },
    'triples': [
        ('{iri}', 'rdf:type', 'vm:{row[class]}'),
        ('{iri}', 'vm:name', '{row[name].as_text}'),
        ('{iri}', 'vm:usesMapTiles',
            'https://opatlas-live.s3.amazonaws.com/ris3-renewals/{version}/'
            'overlays/{row[tile_id].as_text}/{{z}}-{{x}}-{{y}}.png#'
            'background:{row[bg].as_text}'),
        ('{iri}', 'vm:useFilters', '{row[filters].as_text}'),
        ('{iri}', 'vm:followedBy', '{row[following].as_text}'),
        ('{iri}', 'vm:ofStory', 'vm:{row[of_story].as_text}'),
        ('{iri}', 'vm:firstPoint', 'vm:{row[first_point].as_text}'),
        ('{iri}', 'vm:followedBy', 'vm:{row[next_point].as_text}'),
        ('{iri}', 'vm:asOrdinal', '{n}'),
        ('{iri}', 'vm:comment', '{row[geog_id].as_text}'),
    ],
}
