---
name: Gate

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    name: Basic gating validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: install
        run: |
          pip3 install poetry
          poetry config experimental.new-installer false
          poetry install --no-root
      - name: test
        run: |
          make test
      - name: lint
        run: |
          make lint
